name: Psalm Static Analysis

on:
  push:
    paths:
      - '**.php'
      - 'psalm.xml'

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: |
          php -v
          composer install --prefer-dist --no-interaction

      - name: Run Psalm
        run: ./vendor/bin/psalm
